dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
jobs:
  include:
    - python: "3.6"
      env: TOXENV=oldbs4
    - name: flake8
      env: TOXENV=flake8
      before_script:
      after_success:
    - name: check-manifest
      env: TOXENV=check-manifest
      before_script:
      after_success:
    - name: sphinx
      python: "3.6"
      addons:
        apt:
          packages:
            - graphviz
            - mandoc
      install:
        - pip install -r requirements.txt
        - pip install Sphinx sphinx-epytext sphinx-intl sphinx-rtd-theme
      before_script:
        - python3.6 setup.py build
      script:
        - make -C doc code
        - make -C doc html
        - make -C doc locale
        - make -C doc man
        - make -C doc check
      after_success:
# command to install dependencies
addons:
  apt:
    packages:
      - clamav-daemon
      - geoip-database
      - libgeoip-dev
install:
  - pip install tox-travis coveralls
before_script:
  # we need to download the clamav signature database before the daemon will run
  - sudo service clamav-freshclam stop
  - sudo freshclam
  - sudo service clamav-daemon restart
  - sudo service clamav-daemon status
  - while ! test -S /var/run/clamav/clamd.ctl; do printf "."; sleep 1; done
# command to run tests
script:
  - tox
# do not send emails of broken builds
notifications:
  email: false
after_script:
  - coveralls
cache:
  pip: true
  directories:
    - /var/lib/clamav/
